export const DEFAULT_ITEMS_LIMIT = 10

export const DEFAULT_ITEMS_SKIP = 0

export const DEFAULT_PAGES_SKIP = 1

export const DEFAULT_INCREASE_PAGINATION_PAGES_COUNT = 4

export const DEFAULT_DECREASE_PAGINATION_PAGES_COUNT = 1

export const DEFAULT_ACTIVE_PAGE_NUMBER = 1

export const DEFAULT_TOTAL_ITEMS_COUNT = 1

export const ARRAY_DECREASE_INDEX = 1
